const searchQuery = document.getElementById('searchID');
let divName = document.querySelector('#cityName');
let divLon = document.querySelector('#lon');
let divLat = document.querySelector("#lat");
let divCountry = document.querySelector('#country');
let cityText = document.querySelector('#searchBar');
const searchWrapper = document.querySelector('#searchArea');
let citySunrise = document.querySelector('#sunrise');
let citySunset = document.querySelector('#sunset');
let currentT = document.querySelector('#currentTemp');
let feelsL = document.querySelector('#feelsLike');
let sky = document.querySelector('#sky');
let pressureT = document.querySelector('#pressure');
let humidityT = document.querySelector('#humidity');
let windSpeed = document.querySelector('#windSpeed');
let secondaryWrap = document.querySelector('#secondaryInfo');
let teritaryWrap = document.querySelector('#teritaryInfo');
let dateWrapper = document.querySelector('#dateWrapper');
let bg = document.querySelector('#secondaryInfo');
let modalContent = document.querySelector('#modal-content');
let monthArray = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'June', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const atmosphere = ['Mist', 'Smoke', 'Haze', 'Dust', 'Fog', 'Sand', 'Ash', 'Squall', 'Tornado'];
let cID;
let searched = false;
let cidArray = [];
const dataArray = [];
const modal = document.querySelector("#myModal");
const icons  = {
    sun: '<i class="fas fa-sun"></i>',
    rain: '<i class="fas fa-cloud-showers-heavy"></i>',
    cloud: '<i class="fas fa-cloud"></i>',
    sunCloud: '<i class="fas fa-cloud-sun"></i>',
    wind: '<i class="fas fa-wind">',
    snow: '<i class="fas fa-snowflake"></i>',
    humidity: '<i class="fas fa-tint">',
    pressure: '<i class="fas fa-thermometer-half">',
    haze: '<i class="fas fa-smog"></i>'
};